{"uuid": "3e8b27bd-f114-4cd9-9d80-253c2695d2be", "children": ["a8242868-d4b2-406c-b148-01bbddbc5e52"], "befores": [{"name": "start_app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error finding if 'io.appium.uiautomator2.server' is installed. Original error: Error executing adbExec. Original error: 'Command 'D\\:\\\\android-sdk_r24.4.1-windows\\\\android-sdk-windows\\\\platform-tools\\\\adb.exe -P 5037 -s 127.0.0.1\\:52001 shell dumpsys package io.appium.uiautomator2.server' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability\n\n", "trace": "  File \"D:\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"D:\\app_auto_test\\testcases\\conftest.py\", line 18, in start_app\n    driver=base_driver()\n  File \"D:\\app_auto_test\\testcases\\conftest.py\", line 57, in base_driver\n    driver=webdriver.Remote('http://127.0.0.1:4723/wd/hub',caps)\n  File \"D:\\python\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 144, in __init__\n    proxy\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\python\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 219, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1570581121904, "stop": 1570581151137}], "start": 1570581121904, "stop": 1570581151515}