{"uuid": "6f9d9d7a-6453-40df-814c-c656dc35a673", "children": ["4cbbef32-63cc-4ca0-9a72-9ebf1538654f"], "befores": [{"name": "start_app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error waiting for the device to be available. Original error: 'Error executing adbExec. Original error: 'Command 'D\\:\\\\android-sdk_r24.4.1-windows\\\\android-sdk-windows\\\\platform-tools\\\\adb.exe -P 5037 -s 127.0.0.1\\:52001 wait-for-device' exited with code 1'; Stderr: 'error: protocol fault (couldn't read status): Connection reset by peer'; Code: '1''\n\n", "trace": "  File \"D:\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"D:\\app_auto_test\\testcases\\conftest.py\", line 18, in start_app\n    driver=base_driver()\n  File \"D:\\app_auto_test\\testcases\\conftest.py\", line 57, in base_driver\n    driver=webdriver.Remote('http://127.0.0.1:4723/wd/hub',caps)\n  File \"D:\\python\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 144, in __init__\n    proxy\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\python\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 219, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1570581156527, "stop": 1570581244945}], "start": 1570581156527, "stop": 1570581245040}